### ISSUE TITLE
Backend: Лидерборд по уничтожению снежинок

### ISSUE THREAD

**Issue by vasilykg** [vasilykg/BoundlessCelebration#16]
Дать возможность себя назвать (возможно тому кто входит в лидерборд), выводить топ5 лидеров с показателями.

**Comment by DKARAGODIN** [comment]
backend сделан

получить 10 лидеров - curl https://functions.yandexcloud.net/d4edu2a1bae56j6aldbs 
запостить новый результат - curl -X POST https://functions.yandexcloud.net/d4ecqkmrugqls3jbh3f6 -H "Content-Type: application/json" -d '{"name":"Маша","score":235}'

**Comment by vasilykg** [comment]
нам бы еще общие число уничтоженных снежинок

и какая-то нужна возможность сброса тестовых показателей, перед тем как запустим в бой

**Comment by VirusAlex** [comment]
Как будем защищаться от дублирующихся имён? Чтобы скама не было? Генерить UUID при первом открытии страницы?

**Comment by DKARAGODIN** [comment]
общее количество уничтоженных снежинок - curl https://functions.yandexcloud.net/d4e5qu6kvkae75r0e7qt
очистить табличку - curl -X DELETE https://functions.yandexcloud.net/d4ectegf4rsl41d6318p

**Comment by DKARAGODIN** [comment]
> Как будем защищаться от дублирующихся имён? Чтобы скама не было? Генерить UUID при первом открытии страницы?

Да наверное никак. Пусть пишут что хотят и сколько хотят.

**Comment by DKARAGODIN** [comment]
Сделал постинг результатов на бэкенд по клику на снежинку.

**Comment by VirusAlex** [comment]
@DKARAGODIN , смотри, у меня такая идея была
1. Делаем бота в тимсе, который при обращении в личку выдаёт персональный токен (UUID). При этом бот постит нового пользователя в базу с этим UUID и его реальным именем.
2. Человек заходит на нашу страничку, вводит этот UUID и "регистрируется" любым именем.
2а. Если введен несуществующий UUID - то никуда не пускаем.
3. Все результаты снежинок постятся автоматически с этим UUID (например, каждые 10 снежинок).
4. В таблице лидеров светим имя, которое ввели вручную.
5. Можно зайти в этим же UUID зайти с другого браузера - тогда с базы подтягиваем имя и результаты по снежинкам.

В дальнейшем реальное имя можно будет использовать, чтобы сделать список читеров, например, кто накрутил себе снежинок)
Так мы защитим страничку от "левого" использования, защитимся от коллизий по именам. И каждый пользователь будет постить данные только под своим уникальным UUID

**Comment by vasilykg** [comment]
не сложновато ли)

**Comment by vasilykg** [comment]
надо бы где-то задеплоить openapi спеку нашего api... если сделаем в about техническую документацию с figma моделями, openapi спеками, dbdiagrams схемами БД... может получиться интересно)

**Comment by DKARAGODIN** [comment]
Комментарий со всеми рабочими бэкенд функциями:
получить 10 лидеров - curl https://functions.yandexcloud.net/d4edu2a1bae56j6aldbs
запостить новый результат - curl -X POST https://functions.yandexcloud.net/d4ecqkmrugqls3jbh3f6 -d '{"name":"Маша","score":235}'  
Функция сначала делает Select по имени. Если имя такое уже есть, то обновляет запись если новая запись имеет больше снежинок чем раньше. Если имя новое, то делается инсерт в базу. Поддержки многопоточности нет. Если два пользователя одновременно запостят нового пользователя с одинаковым именем, тогда оба будут в базе, увы. MERGE база данных не поддерживает.
общее количество уничтоженных снежинок - curl https://functions.yandexcloud.net/d4e5qu6kvkae75r0e7qt
очистить табличку - curl -X DELETE https://functions.yandexcloud.net/d4ectegf4rsl41d6318p
получить результат по имени curl -X POST https://functions.yandexcloud.net/d4eg7hdbc3d5vf9seb1o -d '{"name":"Маша"}'
Если имя не найдено, то вернется null.
