### ISSUE TITLE
Телефонный layout

### ISSUE THREAD

**Issue by vasilykg** [vasilykg/BoundlessCelebration#24]
С телефона работает норм, но немного наезжают слова в вертикальной и горизонтальной ориентации
![7FF0DE3E-E804-415A-8A1E-C6EF91AB9E53_1_105_c](https://github.com/user-attachments/assets/7f456400-d584-40d5-96c9-16ceb8da9ffe)

**Comment by VirusAlex** [comment]
@vasilykg , теперь должно быть получше

**Comment by vasilykg** [comment]
мелковата на телефоне надпись"С новым годом"... но может и ладно
