### ISSUE TITLE
Выбор платформы для деплоймента

### ISSUE THREAD

**Issue by vasilykg** [vasilykg/BoundlessCelebration#4]
куда там деплоиться модно, чтобы была возможность и серверный код запускать
 
Vercel, Netlify, ...?

предположительно захотим добавить возможность вызывать из серверного кода api методы, например openai

**Comment by VirusAlex** [comment]
Можно прям тут задеплоиться через Insights, прям из репозитория на github io

**Comment by VirusAlex** [comment]
Точнее, через Pages
