### ISSUE TITLE
Подвинуть статус бар

### ISSUE THREAD

**Issue by vasilykg** [vasilykg/BoundlessCelebration#7]
Веселый статус бар подвинуть в центр, чтобы им стала надпись "Подождите, поздравления загружаются..."

<img width="1390" alt="Screenshot 2024-12-12 at 16 06 02" src="https://github.com/user-attachments/assets/629830a1-e63b-4755-a7f6-e9d23520d306" />

**Comment by VirusAlex** [comment]
Сделал пул

**Comment by VirusAlex** [comment]
Только там ещё один пул надо замержить
